import styles from '../styles/Home.module.css'
import { Footer } from '../components/footer'
import { Header } from '../components/header'
import Location from './location'

function About() {
    return (
        
        <div className={styles.title}>
        <Header />
        <div>
      < main className={styles.main}>
        <title>Renaissance Tatoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/renai.png" />
        <div className={styles.backImg}>
        <div className={styles.heroabout}>
          <p>
            Ещё раз приветствую тебя на моём сайте !
          </p>
          <p>
            <ul>
            <li> Я уже давно не начинающий тату мастер.</li>
            <li>У меня больше двух лет опыта и художественное образование.</li>
            <li>Если ты давно хотел набить себе тату,тогда пиши мне в телеграм или инстаграм.</li> 
            <li>Или может ты хочешь быть уникальным ?</li>
            <li>Я могу тебе предложить создать эскиз по всем твоим критериям.</li>
            <li> Дажe Мама и Папа оценят, поверь ;)</li>
            <li>Но как и у любого профессионала своего дела у меня есть свои требования.</li>
            <li>Пожалуйста проверь наличие всех пунктов в списке !</li>
            </ul>
          </p>
          <div>
          <p>
            До сеанса нужно :
            <ul className={styles.session}>
              <li>Не употреблять алкоголь и другие вещества</li>
              <li>Хорошо поспать</li>
              <li>Хорошо поесть</li>
              <li>Хорошее самочувствие</li>
              <li>Скинуть предоплату</li>
            </ul>
          </p>
          
        </div>  
        </div>   
        </div>
      </main>
    </div>

      <footer className={styles.footer}>
        <Location></Location>
      </footer>

    </div>
   
)
}


export default About