import styles from '../styles/Home.module.css'
import { Footer } from '../components/footer'
import { Header } from '../components/header'
import Location from './location'

function About() {
    return (
        <div className={styles.title}>
        <Header />
        <div>
      < main className={styles.main}>
        <title>Renaissance Tatoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/renai.png" />
        <div className={styles.backImg}>
        

           <p>Description</p>
           
           
        </div>
      </main>
    </div>

      <footer className={styles.footer}>
        <Location></Location>
      </footer>

    </div>
)
}


export default About