
import styles from '../styles/Home.module.css'
import { Header } from '../components/header'
import Location from './location'
import Gallery from './carousel'
import Galleryy from './carousecond.js'

export default function Home() {
  return (
<div className={styles.container}>
  <div>  
    <div className={styles.title}>
      <Header/>
    </div>
    <div>
      < main className={styles.main}>


        <title>Renaissance Tatoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/renai.png" />
        <div className={styles.backImg}>
           <Gallery />

           <p>Description</p>
           
           <Galleryy/>
           
        </div>
      </main>
    </div>

      <footer className={styles.footer}>
        <Location></Location>
      </footer>
  </div>  
</div>
  )
}
