
import styles from '../styles/Home.module.css'
import { Header } from '../components/header'
import Location from './location'
import Gallery from './carousel'
import Galleryy from './carousecond.js'

export default function Home() {
  return (
    <html>
    <div className={styles.container}>
    
     
    <div className={styles.title}>
      <Header/>
    </div>
    <div>
      < main className={styles.main}>


        <title>Renaissance Tatoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/renai.png" />
        <div className={styles.carouConfig}><Gallery/></div>
        <div className={styles.backImg}>
        <h1>Renaissance Tattoo</h1>

          <div className={styles.hero}>
              <p>The world of pain and pleasure!</p>
              <p>Hi my name is Alina and I am ...tatoo master .
                As it turned out , I having a great pleasure of beating people. 
                To be more concrete , making tatoos on their bodies .
              </p>
              <a href="/about">Check out my world !</a>
          </div>
          
           
        </div>
      </main>
    </div>
        <div className={styles.carouConf}><Galleryy/></div>

      <footer className={styles.footer}>
        <div><Location></Location>
        </div>
      </footer>
      <div>
    </div>
  </div>
  </html>
  )
}
