import styles from '../styles/Home.module.css'
import { Footer } from '../components/footer'
import { Header } from '../components/header'
import Location from './location'

function MyWorks() {
    return (
        <div className={styles.title}>
        <Header />
        <div>
      < main className={styles.mainabout}>
        <title>Renaissance Tatoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/renai.png" />
        <div className={styles.backImg}>
      
        <ul className={styles.gallery}>
          <li>
            <img src="/photos/p1.jpg" alt=""></img>
            <img src="/photos/p2.jpg" alt=""></img>
            <img src="/photos/p3.jpg" alt=""></img>
          </li>
          <li className={styles.gallery}>
            <img src="/photos/p4.jpg" alt=""></img>
            <img src="/photos/p5.jpg" alt=""></img>
            <img src="/photos/p6.jpg" alt=""></img>
          </li>
          <li className={styles.gallery}>
            <img src="/photos/p7.jpg" alt=""></img>
            <img src="/photos/p8.jpg" alt=""></img>
            <img src="/photos/p9.jpg" alt=""></img>
          </li>
        </ul>
           
           
        </div>
      </main>
    </div>

      <footer className={styles.footer}>
        <Location></Location>
      </footer>
    </div>
)
}


export default MyWorks